### ISSUE TITLE
Correct "Official Holidays of Iran, Islamic Republic of" for 1394 jalali year

### ISSUE THREAD

**Issue by AmirKarimi** [ilius/starcal#12]
It seems that "Official Holidays of Iran, Islamic Republic of" doesn't work correctly in 1394 as it shows 5th Farvardin as holiday which is incorrect.

**Comment by ilius** [comment]
It can't be because of that plugin, 5th Farvardin has never been holiday
Please paste the contents of this file
~/.starcal2/core.conf
or send it to my email

**Comment by AmirKarimi** [comment]
Here the `core.conf` file
```
version='2.3.4'

allPlugList=[
  loadPlugin('/usr/share/starcal2/plugins/iran-jalali.spg', enable=True, show_date=False),
  loadPlugin('/usr/share/starcal2/plugins/iran-gregorian.spg', enable=True, show_date=False),
  loadPlugin('/usr/share/starcal2/plugins/iran-hijri.spg', enable=True, show_date=False),
  loadPlugin('/usr/share/starcal2/plugins/iran-ancient.spg', enable=False, show_date=False),
  loadPlugin('/usr/share/starcal2/plugins/iran-jalali-2.spg', enable=False, show_date=False),
  loadPlugin('/usr/share/starcal2/plugins/iran-gregorian-2.spg', enable=False, show_date=False),
  loadPlugin('/usr/share/starcal2/plugins/iran-hijri-2.spg', enable=False, show_date=False),
  loadPlugin('/usr/share/starcal2/plugins/pray_times.py', enable=False, show_date=False),
  loadPlugin('/usr/share/starcal2/plugins/holidays-iran.hol', enable=True, show_date=False),
]

plugIndex=[1, 2, 3, 4, 5, 6, 7, 8]
calTypes.activeNames=['jalali', 'gregorian']
calTypes.inactiveNames=['hijri', 'julian', 'gregorian_proleptic', 'indian_national', 'ethiopian']
holidayWeekDays=[5]
firstWeekDayAuto=False
firstWeekDay=6
weekNumberModeAuto=False
weekNumberMode=7
debugMode=False
```

And I've also attached an screen shot of the program:
![screenshot from 2015-03-29 23 54 14](https://cloud.githubusercontent.com/assets/2813838/6887253/f6137942-d66e-11e4-9df7-013a7763d008.png)

**Comment by ilius** [comment]
شهادت حضرت فاطمه چهارم فروردین باید باشه نه پنجم
Something is wrong with your Hijri (Islamic) calendar configuration
Please run this command: rm ~/.starcal2/hijri-monthes.json
Then quit the program, and run it again

**Comment by AmirKarimi** [comment]
There is no json file in my `~/.startcal2` folder! I'm using version 2.3.4.

**Comment by ilius** [comment]
Please paste the contents of file ~/.starcal2/hijri.conf

**Comment by AmirKarimi** [comment]
```
hijriAlg=0
hijriUseDB=True
```

**Comment by ilius** [comment]
Oh, I just realized your version is too old
Install StarCalendar 2.4.1 and the problem will be fixed
Please follow the releases feed to keep up to date:
https://github.com/ilius/starcal/releases.atom

**Comment by ilius** [comment]
It's better to Git clone master (stable) branch
Or download the snapshot if you don't have Git:
http://github.com/ilius/starcal/tarball/master

**Comment by AmirKarimi** [comment]
Thanks. I'm sorry I didn't update Starcal first. The following command fixed the problem:

```
git pull
sudo ./uninstall
sudo ./install-ubuntu
```
Note: Already cloned the repo

**Comment by ilius** [comment]
No problem
You also don't have to run "uninstall" when updating

**Comment by AmirKarimi** [comment]
Actually I just ran the `install-ubuntu` at first, but it caused the Starcal shortcut to run two instances of program!

**Comment by ilius** [comment]
You can run as many instances as you want for one installation. Starcal does not check if another instance is running or not.
But only one rpm/deb starcal package will be installed. Even if you run install-debian many times
If you run both "install" and install-debian scripts, you will have two installations.
"install" script is only for package-wise unsupported distributions like Slackware and gentoo.

**Comment by AmirKarimi** [comment]
Yes! I accidentally run `install` instead of `install-ubuntu` but immediately terminated the program. It seems that I wasn't fast enough ;)

Thanks for your support and explanation.
