### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by A-Shahbazi** [ilius/starcal#14]
Hi.

Would you mind adding ‍‍‍```python-appindicator``` as ubuntu deb package dependency?
(I'm using starcal 2.4.1 and it took me some time to discover why it's not working.)

Thanks for your great work!

**Comment by ilius** [comment]
Hi
If you use "install-ubuntu" script, that package will be installed automatically
The deb package we create for starcal, is one for all Debian-based distributions
Unless we create a separate package for Ubuntu *just* for adding "python-appindicator" as dependency, which is not worth it I think. After all I'm only a developer.
