### ISSUE TITLE
خطا در بخش ترجیحات - حساب ها

### ISSUE THREAD

**Issue by rastikerdar** [ilius/starcal#16]
![screenshot from 2015-12-29 23-56-50](https://cloud.githubusercontent.com/assets/3116038/12041601/005a44de-ae88-11e5-81cf-e0d68a56ea33.png)

دکمه اضافه را که می زنم اتفاقی نمی افتد اما در ترمینال این خطا را می دهد:

‍‍‍‍‍‍```
Traceback (most recent call last):
  File "/usr/share/starcal3/scal3/ui_gtk/preferences.py", line 1136, in accountsAddClicked
    account = AccountEditorDialog(parent=self).run()
  File "/usr/share/starcal3/scal3/ui_gtk/event/account_op.py", line 38, in __init__
    self.account = event_lib.classes.account[defaultAccountTypeIndex]()
IndexError: list index out of range
```
Debian OS
Python3 3.4.3+
Python3-gi 3.18.2.2

نصب کاملا خام StarCalendar

**Comment by ilius** [comment]
قسمت حساب‌ها فعلاً بخاطر مشکلاتی در استفاده از
Google API
برای کاربران قابل استفاده نمی‌باشد
