### ISSUE TITLE
اندازه قلم روز ها و مناسبت ها ریز و غیر قابل تغییر است

### ISSUE THREAD

**Issue by rastikerdar** [ilius/starcal#18]
![screenshot from 2015-12-30 00-09-58](https://cloud.githubusercontent.com/assets/3116038/12041899/e6fc2ec8-ae8a-11e5-929d-1a4e22123f7b.png)

مناسبت ها را بسیار ریز نشان می دهد. دلیل تغییر اندازه در روز های مختلف را هم متوجه نشدم!
همچنین در قسمت ترجیحات - ظاهر برنامه که اندازه فونت را زیاد می کنم همه چیز بزرگ می‌شود اما هیچ اندازه ای در قسمت اصلی یا مرکزی یعنی همان محیط تاریک تغییر نمی کند و اندازه نوشته ها و ارقام ثابت می ماند.

![untitled](https://cloud.githubusercontent.com/assets/3116038/12041916/0aae8438-ae8b-11e5-8676-549a64fd5898.png)

starcal3

**Comment by ilius** [comment]
در پنجرهٔ شخصی‌سازی، قسمت تقویم هفتگی، می‌توانید تیک « متن رویدادها » را غیرفعال کنید تا کل فضای عرضی به افزونه‌ها اختصاص پیدا کند
همینطور با کلیک بر روی « شخصی‌سازی -> تقویم هفتگی » پارامتر  «مقیاس اندازهٔ متن » قابل تغییر است

**Comment by rastikerdar** [comment]
![screenshot from 2015-12-30 21-03-10](https://cloud.githubusercontent.com/assets/3116038/12054431/d916d96c-af38-11e5-80ea-3e55d460473a.png)

تلاشم نتیجه نداد. نمیدونم فقط برای من اینطوریه؟

**Comment by ilius** [comment]
خب دیگه نمیشه کاریش کرد
باید عرض پنجره رو بیشتر کنید تا فونت متن بزرگتر بشه
