### ISSUE TITLE
امکان نمایش پنجره زمان کلیک بر روی آیکون نوار وضعیت در محیط گنوم ۳

### ISSUE THREAD

**Issue by rastikerdar** [ilius/starcal#19]
این حالت در محیط گنوم ۳ فکر می کنم بیشتر مورد انتظار باشد مثل سایر برنامه از جمله 
StarDict:
کلیک راست = منو
کلیک چپ = نمایش پنجره
کلیک دوباره چپ = پنهان شدن پنجره

اگر درست خاطرم باشد یک بار سالهای پیش در قسمت نظرات وبلاگتون توضیح دادین به خاطر اوبونتو این شکلی هست اما فکر می کنم بشه توی برنامه کاریش کرد یعنی برنامه خودش تشخیص بده در چه محیطی اجرا شده و عکس العمل مقتضی را نشان بده.

**Comment by ilius** [comment]
سلام
همونطور که قبلاً توضیح دادم در
App Indicator
اوبونتو و اپلت‌های گنوم ۳ اصلا راست‌کلیک تعریف نشده
این بخاطر فلسفهٔ
Touch-friendly
بودنش هست که من خودم مخالفم چون سیستم‌عامل دسکتاپ هست و نباید محدود بشه
و هیچ کاری از دست من در این مورد بر نمیاد
چون سیگنال مجزایی برای راست‌کلیک و چپ‌کلیک فرستاده نمیشه به برنامه

**Comment by rastikerdar** [comment]
اما چرا تو بقیه اینطوری نیست؟
Audacious, Stardict ...

**Comment by ilius** [comment]
استاردیکت که از
Tray Icon
استفاده می‌کنه

Audacious
رو نمی‌دونم

این چیزی که گفتم رو در مورد اوبونتو مطمئن هستم که ممکن نیست
ولی توی گنوم ۳ شاید امکان‌پذیر باشه

اکستنشن گنوم ۳ رو آقای هدایت وطن‌خواه نوشتن و توی پکیج فدورای نسخهٔ 2.4.1 گذاشتن
ولی در حال حاظر از وضعیتش بی‌خبر هستم
ftp://www.rpmfind.net/linux/RPM/fedora/updates/testing/20/ppc/starcal-2.4.1-1.fc20.noarch.html
https://hedayat.fedorapeople.org/misc/starcal-gnome-shell-extension/


ضمنا در مورد اپلت گنوم ۳ فکر می‌کنم محدودیت وجود داره چون با پایتون نمیشه پیاده‌سازی کرد بلکه از طریق جاوااسکریپت به پایتون وصل میشه

**Comment by ilius** [comment]
Tue Jan 27 2015 Hedayat Vatankhah - 2.4.0-2
        Drop gnome shell extension: doesn't work correctly with gnome shell 3.14, and replacements are available

این چیزی هست که آقای وطن‌خواه نوشتن
ولی خاطرم نیست راه‌حل جایگزین چی بود یا هست
