### ISSUE TITLE
امکان نمایش مختصر با نگه داشتن موشی روی آیکون نوار وظیفه - Tooltip

### ISSUE THREAD

**Issue by rastikerdar** [ilius/starcal#20]
اینکه بتوان با نگه داشتن موشی یا همان ماوس روی آیکون در ناحیه اعلان، علاوه بر نمایش تاریخ و ... مواردی که در پایین پنجره اصلی نمایش می‌یابد یعنی مناسبت و اوقات شرعی را هم مشاهده کرد و نیازی به کلیک یا نمایش پنجره اصلی نباشد.
Tooltip

**Comment by ilius** [comment]
سلام
این امکان در حال حاضر وجود دارد
ترجیحات -> افزونه‌ها -> نمایش در نماد وضعیت

**Comment by rastikerdar** [comment]
منظورم کلیک نبود. صرفا با بردن موشی روی اون
مثلا زمانی که شما مکان نما رو می بری روی دکمه ها یه  کادر کوچک شامل توضیح اون دکمه نمایش میده
Tooltip

ترجیحا هم بدون تاخیر نشون بده.

**Comment by ilius** [comment]
* Tue Jan 27 2015 Hedayat Vatankhah <hedayat.fwd+rpmchlog@gmail.com> - 2.4.0-2
  - Drop gnome shell extension: doesn't work correctly with gnome shell 3.14, and
    replacements are available

این چیزی هست که آقای وطن‌خواه نوشتن
ولی خاطرم نیست راه‌حل جایگزین چی بود یا هست

**Comment by ilius** [comment]
لطفاً اون چیزی که نوشتم رو تست کنید

**Comment by rastikerdar** [comment]
انجام داده ام! نشده است برادر!
![screenshot from 2015-12-30 21-13-44](https://cloud.githubusercontent.com/assets/3116038/12054634/5a2e718a-af3a-11e5-94b8-bf2fc01a2638.png)

تایید کردم اما اون پایین وقتی موشی روی آیکون می برم روش چیزی نشون نمیده مگر اینکه کلیک کنم!

**Comment by ilius** [comment]
پس کلا تولتیپ نشون نمیده؟
اون
Tray Icon
هست؟

**Comment by ilius** [comment]
تغییرات گنوم ۳ سریع بوده در سال‌های اخیر و من هم خودم ازش استفاده نمی‌کنم و مشغلهٔ زیادی هم دارم
به همین دلیل از این جریان کاملاً عقب هست
اگر فرصت کردم دوباره در گنوم ۳ تست می‌کنم

برای خودم که
Tray Icon
بدون مشکل کار می‌کنه

**Comment by rastikerdar** [comment]
شاید هم مشکل از گنوم ۳ من باشه. چون کلا گنوم ۳ هر نسخه جدیدش بیشتر گند میزنه! خیلی دارن بد گسترش می دن! من فقط به خاطر سادگی و راحتیش دوسش دارم اما مشکلاتش کم نیست. قبلا مشکلات خیلی کمتر بود.
کی دی ای از گنوم بدتر!

**Comment by ilius** [comment]
Tooltip e StarDict kar mikone?

**Comment by rastikerdar** [comment]
برای اینکه مطمئن بشم رفتم توی
XFCE
دیدم همه آیکون ها تولتیپ نشون میدن به جز استارکل. اما چیز مهمی نیست سعید جان. احتمال خیلی زیاد مشکل از جی تی کی یا گنوم من باشه چون هر بار آیپدیت میکنم چیزای عجیب و غریب زیاد پیش میاد. ممکنه با آپدیت بعدی خیلی راحت مشکل حل بشه.
ممنون

**Comment by ilius** [comment]
بی‌زحمت برنامه رو توی ترمینال اجرا کن ببین اروری نشون نمیده
