### ISSUE TITLE
نیاز به بازنگری در تجربه و رابط کاربری - GUI

### ISSUE THREAD

**Issue by rastikerdar** [ilius/starcal#22]
چیدمان و نحوه نمایش موارد و گزینه ها از اصولی خاصی پیروی نمی کند. در اغلب پنجره ها با نمایشی شلوغ و نامرتب مواجه می شوید:
![screenshot from 2015-12-30 01-32-47](https://cloud.githubusercontent.com/assets/3116038/12042989/9004ff72-ae95-11e5-9257-9b46ea65c58e.png)
---------------------------------------
![screenshot from 2015-12-30 01-31-04](https://cloud.githubusercontent.com/assets/3116038/12042990/90b704c4-ae95-11e5-8bf3-f457565bc60e.png)
---------------------------------------
![screenshot from 2015-12-30 01-27-03](https://cloud.githubusercontent.com/assets/3116038/12043001/a43208d2-ae95-11e5-9a05-8207b228aff6.png)

---------------------------------------
مثلا در پنجره ترجیحات سایر برنامه ها این نظم را مشاهده می کنید:
![screenshot from 2015-12-30 01-40-02](https://cloud.githubusercontent.com/assets/3116038/12043071/617c3b1a-ae96-11e5-89ba-2a05e01b38bd.png)
---------------------------------------
![screenshot from 2015-12-30 01-36-16](https://cloud.githubusercontent.com/assets/3116038/12043082/78b8c190-ae96-11e5-9047-1776beb94943.png)
---------------------------------------
![screenshot from 2015-12-30 01-53-43](https://cloud.githubusercontent.com/assets/3116038/12043218/389eb590-ae98-11e5-997c-58a97c6920fe.png)

فکر می کنم نیاز به یک بازنگری کلی هم در پنجره اصلی و هم ثانوی مثل ترجیحات و رویدادها و ... می باشد.
کار کردن با برنامه راحت و ساده نیست. به نظرم تا حدودی گنگ است. مثلا در قسمت رویداد ها مقداری طول کشید تا بفهمم چجوریه. اما در سایر برنامه ها به مراتب راحت تر است.

توصیه من اینه که موقع طراحی ظاهر برنامه:
۱. حتما به سایر برنامه های معروف نگاهی بیندازید
۲. خودتان را جای یک فرد کاملا معمولی و بی اطلاع از همه چیز بگذارید

قابلیت های برنامه خیلی زیاد شده اما حس خوب و شیرینی رو ایجاد نمی کنه.

**Comment by ilius** [comment]
سلام
ممنون از پیشنهادتون
ولی من یک برنامه‌نویس هستم
و این قابلیت‌ها رو تقریباً در کمترین فضای ممکن جا دادم
اگر امکان داره، چیدمان پیشنهادی خودتون رو، با حفظ امکانات فعلی، بصورت
mockup
بکشید و بگذارید تا بررسی کنم
با تشکر

**Comment by rastikerdar** [comment]
خودمونیم ها سعید خان! شیوه تعاملیت توی ایشوها دلسرد کننده است ;)

موید باشی

**Comment by ilius** [comment]
راستش در وضعیت خوبی نیستم
ولی کاری که از دستم بر بیاد رو انجام میدم
