### ISSUE TITLE
مشکل tray icon در پلاسما ۵.۵.۵

### ISSUE THREAD

**Issue by unnamed11** [ilius/starcal#25]
![1](https://cloud.githubusercontent.com/assets/3128705/13611091/06b9de3c-e576-11e5-9640-a3d32e3aee6f.png)
در پلاسما ۵ آیکون سیس تری خیلی کوچیکه به طوری که تاریخ اصلا قابل خوندن نیست. ظاهرا در ال اکس کیوت هم همینجوره

**Comment by ilius** [comment]
ترجیحات -> ظاهر -> نماد وضعیت -> اندازهٔ ثابت
تیک این گزینه را بزنید
