### ISSUE TITLE
اشتباه در مناسبت اربعین

### ISSUE THREAD

**Issue by Sosha1996** [ilius/starcal#30]
امروز ۳۰آبان هست که اربعین هستش اما توی برنامه سه شنبه روز اربعین نوشته شده!
تاریخ های روز های بعد رو هم با سایت تایم.آی‌ار بررسی کردم دیدم در مناسبت تاریخ های بعدی هم اشکال وجود داره
هشتم آذر رحلت رسول اکرم؛شهادت امام حسن مجتبی علیه السلام و روز تعطیل هست که توی برنامه چیزی ننوشتید و تعطیل هم نیست و بجاش تو روز چهارشنبه نوشتید که اونم تعطیل نزدید!
روز بعدی چهارشنبه هست که شهادت امام رضا هست و در روز پنجشنبه نوشتید که این هم روز تعطیل ننوشتید تو برنامه و این هم رو بجاش تو روز پنجشنبه نوشتید...
روز بعدی ها هم همین مشکلات مشابه رو دارن!

...موفق باشید

**Comment by ilius** [comment]
لطفاً چک کنید که تیک این گزینه خورده باشه:
ترجیحات -> پیشرفته -> استفاده از دادهٔ طول ماه‌های قمری

همینطور از آخرین کدهای برنچ
master
استفاده کنید

**Comment by Sosha1996** [comment]
والا زبان فارسی بوده، خوده سیستمم اصلا فارسی هستش، جز تیکه تعطیلات رسمی بقیه چیز ها درست بود و حتی روز شروع هفته شنبه و روز تعطیل هفته هم جمعه بود

**Comment by ilius** [comment]
اگر رویداد خاصی اضافه نکردید یک بار پوشهٔ تنظیمات رو پاک کنید یا تغییر نام بدید

    mv ~/.starcal3 ~/.starcal3.bak

و برنامه رو دوباره اجرا کنید
و زبان فارسی رو انتخاب کنید
تیک
Import configurations
رو هم (اگر فعال بود) بردارید

**Comment by Sosha1996** [comment]
مجددا همه کار ها رو از اول انجام دادم و نسخه جدید رو هم باز گرفتم درست شد :)
تشکر
