### ISSUE TITLE
Arch aur package

### ISSUE THREAD

**Issue by mostafaasadi** [ilius/starcal#35]
سلام
تشکر ویژه برای برنامه خوب و عالیتون 
پکیج https://aur.archlinux.org/packages/starcal/ تحت نظر شماست ؟
الان این پکیج روی نسخه ۳٫۰۴  است و آپدیت نشده است 
باتشکر

**Comment by ilius** [comment]
سلام
ممنون
نخیر تحت نظر من نیست
من فقط اسکریپت‌های نصب داخل پروژه رو مینتین می‌کنم
از اسکریپت
install-archlinux
استفاده کنید
