### ISSUE TITLE
استفاده از تصویر زمینه دسکتاپ

### ISSUE THREAD

**Issue by kiamazi** [ilius/starcal#36]
<p dir="rtl">
انتخاب کردن استفاده از تصویر زمینه میزکار باعث میشه تقویم ماه نمایش داده نشه
</p>
ubuntu16.10, unity7

**Comment by ilius** [comment]
با تشکر از گزارش
این قابلیت هنوز در
Gtk3
پیاده‌سازی نشده و کار نمی‌کنه

**Comment by ilius** [comment]
با توجه به اینکه اون باگ برطرف شده
ولی امکان استفاده از تصویر میزکار بستگی به محیط دسکتاپ داره
و تعداد محیطهای دسکتاپ افزایش پیدا کرده
و حتی در نسخهٔ 2.4 هم باعث کندی برنامه می‌شد
فعلا قصدی برای پیاده‌سازی این قابلیت ندارم
