### ISSUE TITLE
مشکل نصب و ارور جاوا

### ISSUE THREAD

**Issue by Rasoul-Karimi** [ilius/starcal#42]
سلام این ارور رو دارم که میدونم برای جاوا هستش و نصب نمیشه کرد جاوا رو چون ما تحریم هستیم ازاونور! نمیدونم واقعا چیکار کنم دستی هم دانلد کردم نصب کردم اوپن جی دی کی رو هم نصب کردم بازم این ارور رو دارم! اگر راه حلی دارید ممنون میشم بگید

`download failed
Oracle JDK 8 is NOT installed.
dpkg: error processing package oracle-java8-installer (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 oracle-java8-installer
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by ilius** [comment]
ارتباطش به استارکلندر چی هست؟

**Comment by Rasoul-Karimi** [comment]
فکر کنم شما عنوان رو نخوندی! نوشتم مشکل نصب و ارور جاوا! مشکل نصب استارکلندر و ارور جاوا !! خیلی واضحه. موقع نصب ارور میگیرم ارور جاوا و بیانشم کردم

**Comment by ilius** [comment]
جاوا جزو نیازمندی‌های استارکل نیست
و هیچ ربطی به استارکل نداره
احتمالا مشکل از
apt/dpkg
شما هست

**Comment by Rasoul-Karimi** [comment]
ولی این ارور رو داد و نصب هم نشد! نصب بشه کنار تاریخ خود اوبونتو باید تاریخ شمسی رو هم داشته باشم دیگه درسته؟ اتومات اضافه میشه درست میگم؟ در حالی که اینطور نشد و ارور هم گرفتم همونی که تو پست اولم گذاشتم! نمیدونم جاوا هم مارو تحریم کردم از اونور نمیشه نصبش کرد حکایتی داریم ما با اینا!

**Comment by ilius** [comment]
دستور
starcal3
رو اجرا کنید
اگر
command not found
داد، دوباره نصب کنید با این دستور
cd starcal
sudo ./install-debian
و خروجی کامل رو بذارید

**Comment by Rasoul-Karimi** [comment]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'gir1.2-appindicator3-0.1' for glob 'gir1.2-appindicator3*'
gir1.2-appindicator3-0.1 is already the newest version (12.10.1+16.04.20170215-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 44 not upgraded.
./install-debian: line 27: /home/karimi/Downloads/Untitled: No such file or directory
/home/karimi/Downloads/Untitled Folder 2/ilius-starcal-04e0806/install: line 28: /home/karimi/Downloads/Untitled: No such file or directory
dpkg-deb: error: parsing file '/tmp/starcal3-install-deb/DEBIAN/control' near line 2 package 'starcal3':
 error in 'Version' field string '': version string is empty

**Comment by ilius** [comment]
نام دایرکتوری
Untitled Folder 2
رو تغییر بدید و فاصله رو حذف کنید

در برنچ مستر برطرف شد
