### ISSUE TITLE
گیر کردن دکمه‌های هفته قبل و بعد

### ISSUE THREAD

**Issue by MJafarMashhadi** [ilius/starcal#44]
**نسخهٔ تقویم**
 ```
3.0.6
```
**دسکتاپ**
 ```
GNOME Shell 3.24.3
```
**سیستم عامل**
 ```
 fedora 25 x86/64
```
**زبان**
```
فارسی
```

**شرح اشکال:**

دکمه‌های هفتهٔ بعد و هفتهء قبل به صورت کلیک شده باقی می‌مانند (در صورتی که کلیک موس رها شده) و مرتب به کار خود (تغییر هفته) به صورت ناخواسته ادامه می‌دهند.

**نحوهٔ بازتولید:**

روی دکمه دابل کلیک کنید و بلافاصله موس را حرکت دهید تا cursor به شکل «دست مشت شده» تغییر پیدا کند.
 کلیک را رها کنید.

**Comment by ilius** [comment]
Please try again.
Thanks
