### ISSUE TITLE
تقویم شمسی پیش از ورود به سیستم

### ISSUE THREAD

**Issue by goodosuser** [ilius/starcal#46]
سلام
خوبه بشه با استفاده از همین تقویم صفحه ورود به سیستم هم تقویم شمسی داشته باشه 
الان دیگه ویندوز هم تقویم شمسی داره

**Comment by ilius** [comment]
سلام
متاسفانه امکانش نیست
چون
display manager
های مختلفی وجود داره، و همه با زبان سی یا سی++ نوشته شده‌ان
نه تنها با پایتون نمیشه شخصی‌سازی کرد، بلکه قابلیت پلاگین هم عموما ندارن
یعنی باید خود
gdm
پشتیبانی بکنه
