### ISSUE TITLE
رویدادها قابل تغییر نیستند چون توسط یک پروسه دیگر starcalendar 3 قفل شده‌اند

### ISSUE THREAD

**Issue by mjdtjm** [ilius/starcal#47]
I'm running starcal 3.0.7 on debian 9.3
After running it, I've got the follwoing error:
رویدادها قابل تغییر نیستند چون توسط یک پروسه دیگر starcalendar 3 قفل شده‌اند

But no other starcal3 process is running!

**Comment by ilius** [comment]
Please update to version 3.1.1 and let me know if it happened again
