### ISSUE TITLE
webdav3 support

### ISSUE THREAD

**Issue by mehrtech** [ilius/starcal#51]
Hi dear ilius
Thanks alot for Hard work and great job...
Is there a way to use Star Calendar as a Client Calendar such as Mozilla Thunderbird, Lightning, Cadaver or Evolution Calendar?
I need a Client calendar (jalali/irani, support) that can support the protocol webDav3,
You can help me or any tips, I will be very grateful...

**Comment by ilius** [comment]
Hello
StartCalendar does not support WebDav.
And unless WebDav can support additional calendar types like Jalali, adding this feature is not reasonable.

**Comment by ilius** [comment]
من به سی++ تسلطی ندارم
می‌تونید از یکی از دوستان سی++ کار درخواست کنید
ظمنا بستگی داره که دقیقاً به کدوم قسمت‌هاش می‌خواهید جلالی اضافه بشه

**Comment by mehrtech** [comment]
درود و عرض ادب....
من برنامه ایی در دست استقرار دارم برای بهداشت و درمان که ازیک پلاتفرم (ERP)
بسیار خوب  که با پایتون خالص نوشته شده و دارای ماژول هایی برای مدیریت
بیمارستانی و ثبت اسناد پزشکی و مدیریت آزمایشگاه و... میباشد... این برنامه
دارای ماژول های اختصاصی تقویم درونی است که کلا با پایتون نوشته شده و از
Python3 webDAV library و  webdav server, for Python3 برای تنظیم وقت ویزیت
های بیماران سرپایی و بستری استفاده میکنه... .کاربران راه دور با هر کلایت
کالندر که پرتکل  webdav رو پشتیبانی کنه استفاده کرد ازقبیل ( Mozilla
Thunderbird, Lightning و Cadaver و Evolution و غیره...)...
من فکر میکنم شما و تجربه بسیار عالی تون در گنو/ لینوکس و همچنین پایتون کلید
حل این مشکل باشید...
