### ISSUE TITLE
سازگاری با ویندوز ۱۰

### ISSUE THREAD

**Issue by neesti** [ilius/starcal#52]
سلام.
آیا در برنامه‌های این تقویم هست که نسخهٔ سازگار با ویندوز ۱۰ هم بدهد؟
البته ویندوز ۱۰ تقویم شمسیِ داخلی دارد؛ اما مناسبت‌ها را ندارد و ضمناً اگر تقویم سیستم را شمسی کنیم، دیگر به تقویم میلادی دسترسی نداریم! 
بنابراین وجود تقویمی به‌کاملیِ تقویم شما برای ویندوزکارها خیلی مفید خواهد بود. 
متشکرم.
‌

**Comment by ilius** [comment]
سلام
راستش مدت زیادی هست که برنامه رو در ویندوز تست نکردم
ولی اگر پیش‌نیازهای برنامه رو نصب کنید احتمالا بدون مشکل اجرا میشه

اول باید پایتون 3.6 رو نصب کنید
و بعد Gtk3
و بعد این پکیج‌ها رو با پیپ نصب کنید

pip3 install pygobject
pip3 install httplib2
pip3 install python-dateutil
pip3 install psutil
pip3 install requests

**Comment by ilius** [comment]
برای نصب جی‌تی‌کی
https://www.gtk.org/download/windows.php

مشکل اصلی همین هست که نصب پیش‌نیازها برای کاربران غیرحرفه‌ای کمی سخت هست

**Comment by neesti** [comment]
نمی‌شود همهٔ پیش‌نیازها را در نصاب برنامه گنجاند؟

**Comment by ilius** [comment]
من چند سال پیش تقویم فارسی سان‌کلندر رو تست کردم توی ویندوز و برنامه کاملی هست
مناسبت‌ها رو هم داره
http://psoft.ir

**Comment by ilius** [comment]
نصاب ویندوز که نداریم

**Comment by neesti** [comment]
من یک سؤالی دارم:
مگر نه اینکه در وصف کیوت می‌گویند یک بار کد بنویس و بارها اجرا کن؟
خب پس چرا نمی‌شود با همان کد، نسخهٔ تحت ویندوز این تقویم را هم داشت؟!

**Comment by ilius** [comment]
این برنامه با
Gtk
ساخته شده نه کیوت

ضمنا اون حرف برای جاوا بیشتر صادق هست

در پایتون به کتابخانه‌های مبتنی بر سی نیاز هست
که باید جداگانه برای سیستم‌عامل‌های مختلف کامپایل بشن
و نیاز به نصاب جداگانه برای سیستم‌عامل‌های مختلف داره

حتی برنامه‌های مبتنی بر سی++ و کیوت هم نصاب جدا برای ویندوز دارند

**Comment by neesti** [comment]
آقا من که برنامه‌نویس نیستم و سر در نمی‌آورم. 
فقط لطفاً یک دقیقه برو توی ویندوز و یکی هم برای ما درست کن!
