### ISSUE TITLE
The app doesn't respond to any clicks

### ISSUE THREAD

**Issue by runo280** [ilius/starcal#56]
<div dir="rtl">
نسخه ۳.۱.۱ تقویم رو روی اوبونتو ۱۹.۰۴ نصب کردم، برنامه رو که باز میکنم توی دیالوگ انتخاب زبان هر چی رو دکمه ها و حتی دکمه بستن دیالوگ کلیک میکنم واکنشی نشون نمیده. نمی دونم اگر لاگی جایی ذخیره میشه بفرمایید قرار بدم.
</div>

**Comment by ilius** [comment]
لطفاً دستور
starcal3
رو در ترمینال اجرا کنید، و بعد از زدن دکمه تایید، خروجی یا ارور ترمینال رو اینجا بذارید
ممنون

**Comment by runo280** [comment]
<div dir="rtl">
عجیبه ولی الان که بازش کردم بدون مشکل کار کرد، البته به طور معمول اجراش کردم نه از طریق ترمینال.
حتی این دو تا کار رو قبل ایشو زدن انجام داده بودم (ریبوت سیستم و نصب دوباره برنامه) ولی مشکل داشت اون موقع.
با ترمینال هم باز کردم مورد خاصی نداشت.
متشکر
</div>

**Comment by ilius** [comment]
اگر لطف کنید برای بازسازی کردن باگ، دایرکتوری دیتای برنامه رو دیلیت کنید
rm -rf "$HOME/.starcal3"
و بعد دستور
starcal3
رو توی ترمینال اجرا کنید

**Comment by runo280** [comment]
<div dir="rtl">
همون داستان بچه که وقتی میره پیش دکتر میگه هیچیم نیست، باز تولید نمیشه، حداقل ۵ بار انجام دادم کاری که گفتید، بدون مشکل کارمیکنه.
یبارم حذف و نصب کردم حتی.
شاید ایراد مربوط به اوبونتو بوده.
</div>

**Comment by ilius** [comment]
:)) ممنون
