### ISSUE TITLE
برون‌بری و درون‌ریزی تنظیمات و شخصی‌سازی

### ISSUE THREAD

**Issue by hsabzehmeidani** [ilius/starcal#57]
<div dir="rtl">
سلام

تشکر بابت تقویم خوبی که طراحی کردید

ظاهرا قابلیت برون‌بری و درون‌ریزی تنظیمات و شخصی‌سازی‌ها در برنامه وجود ندارد.

با توجه به این مورد، با داشتن کدام یک از فایل‌های پوشه .starcal3 می‌تونیم اطمینان داشته باشیم که در نصب جدید با جایگزینی آن‌ها ظاهر تقویم مطابق با ظاهر شخصی‌سازی شده‌ی تقویم در سیستم قبلی می‌شود؟

![StarCal](https://user-images.githubusercontent.com/46417001/62819221-9659bd80-bb67-11e9-8485-36cbfe3a514e.png)

موفق باشید.
</div>

**Comment by ilius** [comment]
کافی‌س کل پوشهٔ
~/.starcal3
را کپی کنید
ترجیحات و شخصی‌سازی در فایل‌های با پسوند جیسون ذخیره شده

دو دایرکتوری
objects, event
هم شامل رویدادها
که البته می‌توانید رویدادها را
import, export
کنید
