### ISSUE TITLE
مشکل در صادر کردن به iCalendar

### ISSUE THREAD

**Issue by hsabzehmeidani** [ilius/starcal#58]
<div dir="rtl">
سلام

فایل ics تولید شده از طریق **ترجیحات/افزونه‌ها/تعطیلات رسمی ایران/صادر کردن به iCalendar** به صورت صحیح ایجاد نشده است.
در واقع لازم است بعد BEGIN:VEVENT و END:VEVENT یک n\ بخورد.
گرچه مناسبت‌های اسلامی، هجری و میلادی (تقویم رسمی ایران) صحیح تولید می‌شوند.
مشکل رخ داده یک چیزی مثل این است:
</div>

BEGIN:VEVENTCREATED:***

END:VEVENTBEGIN:VEVENTCREATED:***

**Comment by ilius** [comment]
ممنون از گزارش
لطفاً تست کنید

**Comment by hsabzehmeidani** [comment]
<div dir="rtl">
سلام، خواهش می‌کنم.

مشکل اول حل شد، یعنی عبارت پس از BEGIN:VEVENT در سطر بعد قرار می‌گیرد. ولی مشکل دوم همچنان وجود دارد.

دو عبارتی که لازم است در دو سطر مجزا قرار بگیرند به حالت چسبیده و به صورت END:VEVENTBEGIN:VEVENT در یک سطر نوشته می‌شوند.

هنوز هم لازم است پس از END:VEVENT یک n\ قرار بگیرد.

![ics](https://user-images.githubusercontent.com/46417001/62999460-c2d14a80-be83-11e9-80e5-c4d1ef0cd832.png)

در حال حاضر Google Calendar  و همچنین [iCal Event Maker](https://ical.marudot.com/) خروجی فعلی رو نادرست تشخیص می‌دهند.
</div>

**Comment by ilius** [comment]
اصلاح شد
ممنون

**Comment by hsabzehmeidani** [comment]
<div dir="rtl">
تشکر، لطف کردید.

تازه متوجه شدم که یک خطای نوشتاری هم وجود دارد و لازم است VA0LUE به VALUE تغییر کند.

![ics_VALUE](https://user-images.githubusercontent.com/46417001/63005434-c2d84700-be91-11e9-92ae-d5c83c92ee35.png)
</div>

**Comment by ilius** [comment]
ممنون
