### ISSUE TITLE
Problem with Gnome Wayland

### ISSUE THREAD

**Issue by javadr** [ilius/starcal#61]
I've used your great app for several years without any problems. 
I've recently moved to Manjaro with Gnome 3.36.1 (Wayland). Although it works like a charm in Xorg, it doesn't work in Wayland. I exactly mean it works but doesn't show the icon in the icon bar and thus I have no chance to know about the date! 
Is there any way to open the Starcal window without clicking on the icon (as I can't see it in Wayland)?
Whenever I try to run from the shell it shows me the following message and it is obvious as it's running in my system. 
![Screenshot from 2020-04-18 13-03-11](https://user-images.githubusercontent.com/1178221/79632547-419a2800-8175-11ea-9f8b-1158308eabc7.png)

What should I do now to have access to the calendar?

**Comment by ebrahimradi** [comment]
I have this issue too:

> ~:
> starcal3 
> praytimes: onCurrentDateChange (2020, 5, 8)
> toPreAzanSec=21490.0
> toAzanSecs=21610.0
> toPreAzanSec=33580.0
> toAzanSecs=33700.0
> toPreAzanSec=44460.0
> toAzanSecs=44580.0
> toPreAzanSec=47116.0
> toAzanSecs=47236.0
> Event lock file /home/****/.starcal3/event/lock.json exists, EVENT DATA IS READ-ONLY
> Traceback (most recent call last):
>   File "/usr/share/starcal3/scal3/ui.py", line 362, in getCell
>     return self.jdCells[jd]
> KeyError: 2458978
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/share/starcal3/scal3/event_search_tree.py", line 165, in searchStep
>     raise StopIteration
> StopIteration
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/share/starcal3/scal3/ui_gtk/starcal.py", line 1075, in <module>
>     sys.exit(main())
>   File "/usr/share/starcal3/scal3/ui_gtk/starcal.py", line 1053, in main
>     ui.init()
>   File "/usr/share/starcal3/scal3/ui.py", line 533, in init
>     todayCell = cell = cellCache.getTodayCell() ## FIXME
>   File "/usr/share/starcal3/scal3/ui.py", line 371, in <lambda>
>     getTodayCell = lambda self: self.getCell(core.getCurrentJd())
>   File "/usr/share/starcal3/scal3/ui.py", line 364, in getCell
>     return self.buildCell(jd)
>   File "/usr/share/starcal3/scal3/ui.py", line 373, in buildCell
>     localCell = Cell(jd)
>   File "/usr/share/starcal3/scal3/ui.py", line 310, in __init__
>     self.eventsData = event_lib.getDayOccurrenceData(jd, eventGroups)## here? FIXME
>   File "/usr/share/starcal3/scal3/event_lib.py", line 4156, in getDayOccurrenceData
>     for epoch0, epoch1, eid, odt in group.occur.search(getEpochFromJd(curJd), getEpochFromJd(curJd+1)):
>   File "/usr/share/starcal3/scal3/event_search_tree.py", line 185, in search
>     for mt, dt, eid in self.searchStep(self.root, t0, t1):
> RuntimeError: generator raised StopIteration

**Comment by ebrahimradi** [comment]
Solution:

for the first problem run:

> rm ~/.starcal3/event/lock.json

for the second problem: update the application :laughing:

**Comment by ilius** [comment]
Sorry for long delay.

Do you still have this problem on latest release?

If you don't see the system tray for any reason, there are workarounds:
- Edit `~/.starcal3/ui.json` and change value of `showMain` to `true`, and value of `winTaskbar` to `true`
- Use branch `next`, right-click on the main toolbar and select "Day Calendar (Desktop Widget)", then you should see a small square widget on your desktop that can replace tray / status icon for you.
