### ISSUE TITLE
آیکون جست‌وجو در وقایع

### ISSUE THREAD

**Issue by neesti** [ilius/starcal#63]
<div dir=rtl>
سلام. 

در یادداشت انتشار نسخهٔ 3.1.11 آمده است که آیکون جست‌وجو در وقایع، به نوار ابزارِ منوی اصلی اضافه شده؛ اما نشده! 

_Add "Search Events" icon to Main Window toolbar_

![image](https://user-images.githubusercontent.com/14938202/111438971-1bc92a80-871a-11eb-8c60-ab965a4afc33.png)

**Comment by ilius** [comment]
سلام
ببخشید بابت تأخیر
نمی‌دونم چرا ندیدم ایشو رو

برای فعال کردنش باید پنجرهٔ شخصی‌سازی رو باز کنید و در قسمت «نوارابزار»، مربع جستجوی رویدادها رو تیک بزنید

**Comment by neesti** [comment]
<div dir=rtl>
متشکرم.
