### ISSUE TITLE
Error installing starCal on Debian 11

### ISSUE THREAD

**Issue by mjdtjm** [ilius/starcal#67]
Hello & thanks a lot for your great project.
Installing on Debian 11 reports the following error messages:

This package is uninstallable
Dependency is not satisfiable: python3.8|python3.7|python3.6|python3.5

**Comment by ilius** [comment]
Hi
Please try again with latest `main` branch.
http://github.com/ilius/starcal/tarball/main

**Comment by mjdtjm** [comment]
salAm,
I tried again with the following output messages:
--------------------------------
git version 2.30.2
fatal: not a git repository (or any parent up to mount point /home/mjdtjm)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
WARNING: failed to fetch tags
Using /usr/bin/python3
+ DIR=/tmp/starcal3-install-deb/usr/share/starcal3
+ rm -Rf /tmp/starcal3-install-deb/usr/share/starcal3/.git
+ rm -Rf /tmp/starcal3-install-deb/usr/share/starcal3/.gitignore
+ rm -Rf '/tmp/starcal3-install-deb/usr/share/starcal3/.Trash*'
+ rm -Rf /tmp/starcal3-install-deb/usr/share/starcal3/google-api-python-client/.git
+ rm -Rf '/tmp/starcal3-install-deb/usr/share/starcal3/google-api-python-client/.hg*'
+ find /tmp/starcal3-install-deb/usr/share/starcal3 -name __pycache__ -exec rm -R '{}' ';'
+ find /tmp/starcal3-install-deb/usr/share/starcal3 -type d -empty -delete
+ set +x
dpkg-deb: building package 'starcal3' in 'starcal3_3.1.11-1_all.deb'.
Package file starcal3_3.1.11-1_all.deb created, installing...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: python3-dateutil
----------------------

BTW, why the generated package name instead of "starcal3_3.1.11-18_all.deb" is "starcal3_3.1.11-1_all.deb" ?!

**Comment by ilius** [comment]
Can you install this package manually?
https://packages.debian.org/bullseye/python3-dateutil

- `apt-get update`
- `apt-get install python3-dateutil`

> BTW, why the generated package name instead of "starcal3_3.1.11-18_all.deb" is "starcal3_3.1.11-1_all.deb" ?!
The last number (`1`) is not part of package version, it's the build number.
The full version (for example `3.1.11-18-g8fb6ede2` on main) is only available in git (with presence of `.git`).

**Comment by ilius** [comment]
No worries.
I also updated `install-debian` in `main` branch.
Should be okay now.
