### ISSUE TITLE
flatpak package?

### ISSUE THREAD

**Issue by rezad1393** [ilius/starcal#68]
Is there any plan for a flatpak package?
I am trying to install this app on archlinux but python version checking would not let it to install.
this issue https://github.com/ilius/starcal/issues/66 also says that application is python version dependent.
maybe the best way to deploy this would be with a flatpak.

**Comment by ilius** [comment]
I removed strict version checking in `install` script.
https://github.com/ilius/starcal/commit/5e68c0ca7292d5ef5da0a52b4af6bc0774b4e2dc
