### ISSUE TITLE
به‌روزرسانی ماه‌های قمری

### ISSUE THREAD

**Issue by rastikerdar** [ilius/starcal#71]
در ابتدا تشکر می‌کنم برای این برنامه خوب به ویژه به‌روزرسانی اخیر که ظاهر برنامه خیلی بهتر شده. همچنین در قسمت ترجیحات که یک تحول اساسی و زیبا رخ داده که دستمریزاد. لطفا در آپدیت بعدی این موضوع ماه‌های قمری رو هم در نظر بگیرید.
![Screenshot_2023-03-31_09-55-59](https://user-images.githubusercontent.com/3116038/229041705-c686f599-6e15-459b-a9a3-e8870a0d448e.png)

**Comment by ilius** [comment]
سلام
انجام شد
https://github.com/ilius/starcal/releases/tag/3.2.1
