### ISSUE TITLE
Problem with running Starcal on openSUSE 15.6

### ISSUE THREAD

**Issue by travis-82** [ilius/starcal#75]
Hi

Sarcal3-3.2.3 doesn't run on openSUSE 15.6. During the installation Yast returns this error:

`Error: INVALID:starcal3-3.2.3post1+4bbaab1-1.noarch (file-ae66b3f5): Signature verification failed [6-File is unsigned]
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    MD5 digest: OK
    Package header is not signed!`

This error is not a show stopper and the user can ignore it. However after click on Starcal icon nothing happens. Running starcal3 in terminal returns this error:
`  File "<fstring>", line 1
    (size=)
         ^
SyntaxError: invalid syntax`

Please take a look

**Comment by ilius** [comment]
Is that the entire terminal output / error?
Please paste all of it.
And what is your Python version?

**Comment by travis-82** [comment]
> Is that the entire terminal output / error? Please paste all of it. And what is your Python version?

Yes, that is the entire output. And python3 version in openSUSE 15.6 is 3.6.15

**Comment by ilius** [comment]
That's too old.
You need at least Python 3.8.

**Comment by ilius** [comment]
Does't make any sense!
OpenSUSE 15.6 was released on 2024-06-12.
Python 3.8 was released on 2019-10-14 and reached end of life on 2021-12-23.
We will drop 3.8 as well soon.

**Comment by ilius** [comment]
I'm not a packager.
I don't want to build publish distro packages either.
I'm also not sure how flatpack apps ship gtk stuff.
There is gotta be a way to get newer python on suse.
